apiVersion: v1
description: An Umbrella helm chart for the Official Elastic helm chart
name: elk
version: 8.5.1
appVersion: 8.5.1

dependencies:
- name: elk
  repository: https://github.com/elastic/helm-charts/